### ISSUE TITLE
RSA keys ?

### ISSUE THREAD

**Issue by polto** [romanz/trezor-agent#114]
hi !
I use my Ledger Nano S for SSH authentication. It perfectly works with all of my servers, but not with Cisco routers since they expect only RSA keys.
I can see that ledger SDK support RSA, but the SSH/PGP app only propose to generate ed25519 or nist256p1 keys.  Any idea on how can I generate RSA keys for Cisco's SSHd ?
Regards

**Comment by romanz** [comment]
Currently, my library doesn't support RSA keys (since they aren't supported on TREZOR's firmware).
However, since you're using Ledger Nano S - you should try their [OpenPGP card](https://github.com/LedgerHQ/blue-app-openpgp-card) app, which should support RSA key for SSH authentication IIUC.
CC: @cslashm

**Comment by polto** [comment]
Thanks @romanz ! am downloading the OpenPGP card app.

**Comment by romanz** [comment]
You're welcome :)
