### ISSUE TITLE
gpg: decryption failed: No secret key

### ISSUE THREAD

**Issue by bereska** [romanz/trezor-agent#314]
Ledger Nano X on mac os 10.15.2
gpg-agent.l
[gpg-agent.log](https://github.com/romanz/trezor-agent/files/4042605/gpg-agent.log)
og file attached
thank you

**Comment by bereska** [comment]
is this project dead?

**Comment by virtuaCode** [comment]
I have the same problem when decrypting my sent emails with Enigmail.

- Thunderbird Version 68.2.2
- SSH/PGP Agent Version 0.0.5
- Enigmail Version 2.1.5
- Ledger Nano S Firmware Version 1.6.0
- GPG Version 2.2.4

[gpg-agent.log](https://github.com/romanz/trezor-agent/files/4080561/gpg-agent.log)

PS: The steps described in [enigmail.md](https://github.com/romanz/trezor-agent/blob/master/doc/enigmail.md) are quite outdated

**Comment by feux07** [comment]
This issue may be related to https://github.com/LedgerHQ/ledger-app-ssh-agent/issues/25

**Comment by romanz** [comment]
Sorry for the delayed response... the project is definitely not dead :)
I didn't test the GPG decryption on Ledger Nano X, so thanks for reporting this on https://github.com/LedgerHQ/ledger-app-ssh-agent/.
Closing for now - since IIUC the problem is with the Ledger firmware (seems to return invalid elliptic curve key).

**Comment by bereska** [comment]
thanks for responding and pls keep up the work, it would be great to use ledger nano x apart from a crypto wallet as a U2F, SSH/PGP and maybe even FIDO2 later all in one
