### ISSUE TITLE
Should OnlyKey still be supported?

### ISSUE THREAD

**Issue by doolio** [romanz/trezor-agent#439]
Both the setup.py module and the PyPi page (linked to in the README) both give the same project url namely http://github.com/trustcrypto/onlykey-agent but different versions.

https://github.com/romanz/trezor-agent/blob/3c911e99a0394278104564092225d67c75e74b99/agents/onlykey/setup.py#L6
https://pypi.org/project/onlykey-agent/ states it is v1.1.15.

They OnlyKey team is now using another email namely `admin@crp.to`
https://github.com/romanz/trezor-agent/blob/3c911e99a0394278104564092225d67c75e74b99/agents/onlykey/setup.py#L9
https://github.com/trustcrypto/onlykey-agent/blob/8b60cd00ea60c0ded2925d974fca4dda910a0108/setup.py#L9

They also use their own version of your `libagent` named `lib-agent`:
https://github.com/trustcrypto/onlykey-agent/blob/8b60cd00ea60c0ded2925d974fca4dda910a0108/setup.py#L13
https://pypi.org/project/lib-agent/

They also suggest their package has 'Development Status :: 5 - Production/Stable':
https://github.com/trustcrypto/onlykey-agent/blob/8b60cd00ea60c0ded2925d974fca4dda910a0108/setup.py#L19

So it begs the question whether OnlyKey should still be included in this repo as is because it could lead to confusion for users of that device.

**Comment by romanz** [comment]
Not sure, let's ask @onlykey

**Comment by onlykey** [comment]
OnlyKey should continue to be included as it is still fully supported by the trezor-agent and we plan to continue that support. The reason for lib-agent is that libagent supports only ECC key types and only derived keys. We had discussions about adding support for RSA keys and static keys (bring your own PGP key) to libagent but it seemed to be a large change to libagent when the changes were only for OnlyKey, the other devices don't support this. So that's the reason for lib-agent, for users that want to use PGP/GPG keys  that are loaded to the OnlyKey or for users that want to use RSA keys it has that additional support. For OnlyKey user's that only want the derived ECC keys trezor-agent will continue to be supported.

**Comment by romanz** [comment]
Many thanks!

**Comment by doolio** [comment]
But what about the version number? The version number here differs from the one this module refers to PyPI. Should it at least be aligned and the email address updated? Happy to submit such a PR.
