### ISSUE TITLE
Agent opens TREZOR U2F interface thinking it is regular HID

### ISSUE THREAD

**Issue by prusnak** [romanz/trezor-agent#50]
For some reason you don't use the provided enumerate method, but ended up writing your own. Your code does not perform any check for usage_page nor interface number like defined in our [transport_hid.py](https://github.com/trezor/python-trezor/blob/master/trezorlib/transport_hid.py#L23). This leads to opening U2F interface from time to time resulting in https://github.com/trezor/python-trezor/issues/76

**Comment by romanz** [comment]
IIUC, `HidTransport.enumerate()` is an alias to the correct `enumerate()` function, so the current code should work - by yielding the first interface (wrapped by `ClientWrapper`). 
I think that the issue is not related to the enumeration logic, but is possibly caused by `enumerate()` returning [list(devices.values())] (https://github.com/trezor/python-trezor/blob/master/trezorlib/transport_hid.py#L29), whose order is [unpredictable](https://docs.python.org/2/library/stdtypes.html?highlight=values#dict.items) - which may cause https://github.com/trezor/python-trezor/issues/76.

**Comment by romanz** [comment]
@dmytroleonenko Could you please take a look?
The latest [version](https://github.com/trezor/python-trezor/commit/d1397c779c273997d6e313724500340dc2584b95) of `python-trezor` should have https://github.com/trezor/python-trezor/issues/76 fixed.
