### ISSUE TITLE
Feature: passphrase encrypted private keys.

### ISSUE THREAD

**Issue by ananteris** [romanz/trezor-agent#91]
Is it possible to have the private S/E/C/A keys passphrase encrypted? If so, what are the implications of this if a mnemonic has been compromised?  

One notable questions I can think of regarding this:
Assuming your mnemonic is known to an attacker (but not your PW) and you are suspected to keep your keys on a trezor, would the resulting private key generated from export_keys.py with a different password still effectively be the same keypair? If trezor-gpg-init creates a key, THEN passphrase encrypts the private key (like using --edit-key) it seems that they would be the same keypair. Is there some scheme the mirrors the trezor wallet side of things that guarantee's unique keys based off the password?

Another thing to consider which is probably actually the same as the last issue is whether or not given a trezor and it's mnemonic, could an attacker prove/disprove that a certain key is on a trezor, or otherwise list what keys are on the trezor.

I really like this project, keep up the amazing work.

**Comment by romanz** [comment]
Thanks for the compliments, and the suggested feature!
I have used an empty [passphrase](https://github.com/romanz/trezor-agent/blob/master/trezor_agent/device/trezor.py#L25), mainly for simplicity - but this can be changed to make the scheme more robust to mnemonic leakage.

Of course, in order to extract the private key (as discussed in #88) you'll need to enter the mnenonic **and** the passphrase on the same air-gapped & non-persistent machine - so they won't leak during and after the extraction process.

**Comment by romanz** [comment]
You can now set the passphrase using `TREZOR_PASSPHRASE` environment variable (see https://github.com/romanz/trezor-agent/commit/777524226ffc95d68c600cb7eecf4ff6441e1aa4).

**Comment by edivad13** [comment]
I would like to ask: is there a recommended practice to handle the TREZOR_PASSPHRASE environment variable inside a terminal emulator?

Can for instance unintentionally be kept in the history as many linux distros do by default?

**Comment by AgentME** [comment]
If $HISTCONTROL is set to "ignorespace" or "ignoreboth" (as seems to be standard on Linux), then lines starting with a space aren't saved to the history. You could run " export TREZOR_PASSPHRASE=whatever" before running the gpg commands using the hidden key.
